services:
  user-service: 
    build:
      context: .
      args:
        NODE_ENV: production
    volumes:
      - /app/node_modules
    ports:
      - "4000:4000"
    command: npm run start
  mongo:
    image: mongo
    env_file:
      - ./env/.env
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
