services:
  user-service: 
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - MONGO_USER=user
      - MONGO_PASSWORD=user
    ports:
      - "4000:4000"
    command: npm run dev
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=user
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
